### ISSUE TITLE
Change license from GPL to MIT

### ISSUE THREAD

**Issue by HipsterZipster** [tecfu/smartwrap#12]
Hi,
My team has come to depend on this package given the [recent change in GraphQL Tools](https://github.com/ardatan/graphql-tools/commit/cf86207cbef78241a1c22eebc0a0c69a938f2596) to depend on [`value-or-promise`](https://www.npmjs.com/package/value-or-promise) which indirectly relies on smartwrap. Unfortunately, we cannot leverage GPL licensed dependencies due to legal restrictions. Is it possible to change the license to a more permissive one such as Apache or MIT instead?

PR: https://github.com/tecfu/smartwrap/pull/13

**Comment by tecfu** [comment]
Closed by https://github.com/tecfu/smartwrap/pull/13

**Comment by jonathanj** [comment]
Unfortunately this package [depends on](https://github.com/tecfu/smartwrap/blob/master/package.json#L29) `breakword` which also [had its license changed](https://github.com/tecfu/breakword/commit/fa453115a13708c89078328d2c3184d4ee50cf57), however this change isn't available in a published version of the package.

```
$ npm view breakword@1.0.5 dist.tarball | xargs curl --silent | tar zx -O package/package.json | jq '.license'
"gpl-2.0"
```
